apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
        - name: flow
          env:
            - name: DDB_FTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: ddbftp-credentials
                  key: DDB_FTP_SERVER
            - name: DDB_FTP_USER
              valueFrom:
                secretKeyRef:
                  name: ddbftp-credentials
                  key: DDB_FTP_USER
            - name: DDB_FTP_PWD
              valueFrom:
                secretKeyRef:
                  name: ddbftp-credentials
                  key: DDB_FTP_PWD
            - name: GITHUB_REPO_USER
              valueFrom:
                secretKeyRef:
                  name: github-repo-credentials
                  key: GITHUB_REPO_USER
            - name: GITHUB_REPO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-repo-credentials
                  key: GITHUB_REPO_TOKEN
            - name: PREFECT__CONTEXT__SECRETS__GITHUB_STORAGE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-repo-credentials
                  key: PREFECT__CONTEXT__SECRETS__GITHUB_STORAGE_ACCESS_TOKEN
            - name: MINIO_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ENDPOINT_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY